name: Daily Telegram Sign-in

on:
  schedule:
    - cron: '0 1 * * *'   # 每天 01:00 UTC == 每天 10:00 JST
  workflow_dispatch:     # 手动触发用于测试

jobs:
  send_signin:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon

      - name: Run send_signin
        env:
          TG_SESSION_STRING: ${{ secrets.TG_SESSION_STRING }}
          TG_API_ID: ${{ secrets.TG_API_ID }}
          TG_API_HASH: ${{ secrets.TG_API_HASH }}
          TARGET_USERNAME: '@QingBaoJuXuanwubot'
          SIGN_MESSAGE: '📅 签到'
        run: |
          python scripts/send_signin.py
